### ISSUE TITLE
"Recoverable" Downloading

### ISSUE THREAD

**Issue by CalciferZh** [zhixuany/HUMBI#7]
Hi, thanks for the dataset. I'm wondering if it's possible to make the download "resume-able". As the zips are quite large, it takes hours to download even one file. I found on my side that any network fluctuation may cause an interruption in the download which cannot be resumed - I have to download it from zero again. As a result, I have struggled with this for weeks and haven't managed to download even a single file yet. Is this due to some protocol reason? Would it be possible to make the downloads can be resumed if once paused? Thank you.

**Comment by Gorokke** [comment]
Hi,

I think this is good point. For some reason, currently, we are managing the dataset in a batch level (e.g., 80 subjects at the same time.) We will further discuss this issue and keep you updated. Maybe, one possible option is to manage the file at each subject level (e.g., zipping the file per each subject) and share the donwload script. However, I can't ensure this due to the license issue, I will discuss this with my team and will keep you updated. Thanks! - Jae Shin
